services:

  db:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: MedIntegral
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: